apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: "postgres"
    app: "jira"
  name: "jira-postgres"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "postgres"
  template:
    metadata:
      labels:
        app: postgres
      name: postgres
    spec:
      containers:
        - name: postgres
          image: "postgres"
          env:
           - name: POSTGRES_USER
             value: "jira"
           - name: POSTGRES_DB
             value: "jira"
           - name: POSTGRES_PASSWORD
             value: "jira"  
          volumeMounts:
            - name: "jira-database"
              mountPath: /opt/jira-home
      volumes:
        - name: "jira-database"
          hostPath:
            path: /data/jira/database
