apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jira
  name: jira
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jira
  template:
    metadata:
      labels:
        app: jira
      name: jira
    spec:
      containers:
        - name: jira
          image: "atlassian/jira-software"
          resources:
            requests:
              cpu: "1"
              memory: "1G"
          volumeMounts:
            - name: "jira-home1"
              mountPath: /var/atlassian/application-data/jira
            - name: "jira-shared"
              mountPath: /data/jira/sharedhome  
      volumes:
        - name: "jira-home1"
          hostPath:
            path: /data/jira/home1
        - name: "jira-shared"
          hostPath:
            path: /data/jira/sharedhome
---      
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jira2
  name: jira2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jira2
  template:
    metadata:
      labels:
        app: jira2
      name: jira2
    spec:
      containers:
        - name: jira2
          image: "atlassian/jira-software"
          resources:
            requests:
              cpu: "1"
              memory: "1G"
          volumeMounts:
            - name: "jira-home2"
              mountPath: /var/atlassian/application-data/jira
            - name: "jira-shared"
              mountPath: /data/jira/sharedhome  
      volumes:
        - name: "jira-home2"
          hostPath:
            path: /data/jira/home2
        - name: "jira-shared"
          hostPath:
            path: /data/jira/sharedhome
---      
